import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('styles.css','utf8');
const must=(c,m)=>assert.ok(c,m);
must(!html.includes('images.unsplash.com'),'stock Unsplash images must be removed');
must(html.includes('class="brand brand-original"'),'original-style brand treatment must be present');
must(html.includes('id="video"'),'video section must exist');
must(html.includes('assets/hero-watercolor.svg'),'detailed watercolor hero artwork must be used');
must(html.includes('assets/about-watercolor.svg'),'detailed watercolor about artwork must be used');
must(html.includes('assets/video-poster.svg'),'video artwork must be used');
for(const name of ['early','math','robot','lego','music','school']) must(html.includes(`assets/course-${name}.svg`),`course watercolor image missing: ${name}`);
must(html.includes('name="consent"'),'consent checkbox must exist');
must(html.includes('name="consent" required'),'consent checkbox must be required');
must(html.includes('Согласием на обработку персональных данных'),'consent text must be visible');
must(html.includes('href="consent.html"'),'consent page must be linked from the form');
must(css.toLowerCase().includes('#f2389e'),'original site pink #f2389e must be part of the palette');
must(css.includes('--brand-pink'),'brand palette variables must be declared');
for(const path of ['assets/hero-watercolor.svg','assets/about-watercolor.svg','assets/video-poster.svg','assets/course-early.svg','assets/course-math.svg','assets/course-robot.svg','assets/course-lego.svg','assets/course-music.svg','assets/course-school.svg','consent.html']) must(fs.existsSync(path),`required file missing: ${path}`);
console.log('site acceptance checks passed');
