import fs from "node:fs";
import assert from "node:assert/strict";
const html=fs.readFileSync("index.html","utf8");
const css=fs.readFileSync("styles.css","utf8");
const svg=fs.readFileSync("assets/logo.svg","utf8");
const must=(c,m)=>assert.ok(c,m);
const logos=(html.match(/class="brand-logo"/g)||[]).length;
must(logos>=2,"vector logo must be used in header and footer");
must((html.match(/src="assets\/logo.svg"/g)||[]).length>=2,"header and footer must reference assets/logo.svg");
must(!html.includes('class="brand-sun"'),"old CSS-drawn logo markup must be removed");
must(!html.includes('class="brand-copy"'),"old CSS-drawn logo text must be removed");
must(css.includes('vectorized original logo'),"vector logo CSS must exist");
must(svg.includes('<svg'),"logo.svg must be valid SVG");
must(!svg.includes('<image'),"logo.svg must contain vectors, not embedded raster");
must((svg.match(/<path/g)||[]).length>10,"logo.svg must have traced paths");
must(html.includes('id="video"'),"video section must remain");
must(html.includes('name="consent" required'),"consent checkbox must remain required");
must(html.includes('href="consent.html"'),"consent page link must remain");
must(css.toLowerCase().includes('#f2389e'),"brand palette must remain");
console.log("vector logo acceptance checks passed");
